# Generated by Django 2.1.5 on 2019-09-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_ca_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate_link',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
